export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const FETCH_INGREDIENT_SUCCESS = "FETCH_INGREDIENT_SUCCESS";
export const FETCH_INGREDIENT_FAILURE = "FETCH_INGREDIENT_FAILURE";

export const PLACE_ORDER = "PLACE_ORDER";
export const ORDER_PLACED = "ORDER_PLACED";
export const INITIATE_ORDER = "INITIATE_ORDER";

export const FETCH_ORDERS = "FETCH_ORDERS";
export const ORDERS_LOADING = "ORDERS_LOADING";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
