export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const FETCH_INGREDIENT_SUCCESS = "FETCH_INGREDIENT_SUCCESS";
export const FETCH_INGREDIENT_FAILURE = "FETCH_INGREDIENT_FAILURE";

export const PLACE_ORDER = "PLACE_ORDER";
export const ORDER_PLACED = "ORDER_PLACED";
export const INITIATE_ORDER = "INITIATE_ORDER";

export const FETCH_ORDERS = "FETCH_ORDERS";
export const ORDERS_LOADING = "ORDERS_LOADING";
